<?php
use Illuminate\Database\Seeder;

class PostTagSeeder extends Seeder {
    public function run()
    {
        DB::table('post_tag')->insert(array(
        array('post_id' => 1, 'tag_id' => 1),
        array('post_id' => 2, 'tag_id' => 2),
        array('post_id' => 3, 'tag_id' => 1),
        array('post_id' => 3, 'tag_id' => 3),
        array('post_id' => 3, 'tag_id' => 4),
        array('post_id' => 4, 'tag_id' => 1),
        array('post_id' => 5, 'tag_id' => 2),
        array('post_id' => 6, 'tag_id' => 4),
        array('post_id' => 8, 'tag_id' => 3),
        array('post_id' => 9, 'tag_id' => 4),
        array('post_id' => 10, 'tag_id' => 5),
        array('post_id' => 11, 'tag_id' => 6),
        array('post_id' => 12, 'tag_id' => 7),
        array('post_id' => 13, 'tag_id' => 8),
        array('post_id' => 14, 'tag_id' => 9),
        array('post_id' => 15, 'tag_id' => 10),
        array('post_id' => 16, 'tag_id' => 11),
        array('post_id' => 17, 'tag_id' => 11),
        array('post_id' => 18, 'tag_id' => 15),
        array('post_id' => 19, 'tag_id' => 12),
        array('post_id' => 20, 'tag_id' => 20),
        array('post_id' => 21, 'tag_id' => 1),
        array('post_id' => 22, 'tag_id' => 2),
        array('post_id' => 23, 'tag_id' => 1),
        array('post_id' => 23, 'tag_id' => 3),
        array('post_id' => 23, 'tag_id' => 4),
        array('post_id' => 24, 'tag_id' => 1),
        array('post_id' => 25, 'tag_id' => 2),
        array('post_id' => 26, 'tag_id' => 4),
        array('post_id' => 28, 'tag_id' => 3),
        array('post_id' => 29, 'tag_id' => 4),
        array('post_id' => 30, 'tag_id' => 5),
        array('post_id' => 31, 'tag_id' => 6),
        array('post_id' => 32, 'tag_id' => 7),
        array('post_id' => 33, 'tag_id' => 8),
        array('post_id' => 34, 'tag_id' => 9),
        array('post_id' => 35, 'tag_id' => 10),
        array('post_id' => 36, 'tag_id' => 11),
        array('post_id' => 37, 'tag_id' => 11),
        array('post_id' => 38, 'tag_id' => 15),
        array('post_id' => 39, 'tag_id' => 12),
        array('post_id' => 40, 'tag_id' => 20),
        array('post_id' => 41, 'tag_id' => 1),
        array('post_id' => 42, 'tag_id' => 2),
        array('post_id' => 43, 'tag_id' => 1),
        array('post_id' => 43, 'tag_id' => 3),
        array('post_id' => 43, 'tag_id' => 4),
        array('post_id' => 44, 'tag_id' => 1),
        array('post_id' => 45, 'tag_id' => 2),
        array('post_id' => 46, 'tag_id' => 4),
        array('post_id' => 48, 'tag_id' => 3),
        array('post_id' => 49, 'tag_id' => 4),
        array('post_id' => 50, 'tag_id' => 5),
        array('post_id' => 51, 'tag_id' => 16),
        array('post_id' => 52, 'tag_id' => 12),
        array('post_id' => 53, 'tag_id' => 11),
        array('post_id' => 53, 'tag_id' => 13),
        array('post_id' => 53, 'tag_id' => 15)
    ));
    }
}
?>