<?php

use App\Post;
use Illuminate\Database\Seeder;
use Carbon\Carbon;


class PostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $posts = [
        [
            'user_id' => '1',
            'title' => 'Laravel Installation',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Informatics and Computer Science',
            'status'=> 'Published',
        ],
        [
            'user_id' => '2',
            'title' => 'Food Sustainability',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Business Science: Financial Engineering',
            'status'=> 'Published',
        ],
        [
            'user_id' => '3',
            'title' => 'Database Schemas',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Informatics and Computer Science',
            'status'=> 'Published',
        ],
        [
            'user_id' => '4',
            'title' => 'Do we need more international diplomats',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Arts in International Studies',
            'status'=> 'Published',
        ],
        [
            'user_id' => '5',
            'title' => 'Website Application Development Tools',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Informatics and Computer Science',
            'status'=> 'Published',
        ],
        [
            'user_id' => '5',
            'title' => 'Financial Data Analysis Tools',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Arts in Financial Services',
            'status'=> 'Published',
        ],
        [
            'user_id' => '1',
            'title' => 'Debugging a Heroku application on production',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Informatics and Computer Science',
            'status'=> 'Published',
        ],
        [
            'user_id' => '2',
            'title' => 'Food Sustainability',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Commerce',
            'status'=> 'Published',
        ],
        [
            'user_id' => '6',
            'title' => 'Stock markets analysis',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Commerce',
            'status'=> 'Published',
        ],
        [
            'user_id' => '1',
            'title' => 'Food Sustainability',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Business Science: Actuarial Science',
            'status'=> 'Published',
        ],
        [
            'user_id' => '5',
            'title' => 'Media conglomerates, ownership',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Arts in Communication',
            'status'=> 'Published',
        ],
        [
            'user_id' => '2',
            'title' => 'Police brutality',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Laws',
            'status'=> 'Published',
        ],
        [
            'user_id' => '3',
            'title' => 'Educating special needs students',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Commerce',
            'status'=> 'Published',
        ],
        [
            'user_id' => '1',
            'title' => 'Technology in education',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Commerce',
            'status'=> 'Published',
        ],
        [
            'user_id' => '1',
            'title' => 'Bioterrorism',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Arts in International Studies',
            'status'=> 'Published',
        ],
        [
            'user_id' => '1',
            'title' => 'Laravel Installation',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Informatics and Computer Science',
            'status'=> 'Published',
        ],
        [
            'user_id' => '2',
            'title' => 'Food Sustainability',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Business Science: Financial Engineering',
            'status'=> 'Published',
        ],
        [
            'user_id' => '3',
            'title' => 'Database Schemas',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Informatics and Computer Science',
            'status'=> 'Published',
        ],
        [
            'user_id' => '4',
            'title' => 'Do we need more international diplomats',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Arts in International Studies',
            'status'=> 'Published',
        ],
        [
            'user_id' => '5',
            'title' => 'Website Application Development Tools',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Informatics and Computer Science',
            'status'=> 'Published',
        ],
        [
            'user_id' => '5',
            'title' => 'Financial Data Analysis Tools',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Arts in Financial Services',
            'status'=> 'Published',
        ],
        [
            'user_id' => '1',
            'title' => 'Debugging a Heroku application on production',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Informatics and Computer Science',
            'status'=> 'Published',
        ],
        [
            'user_id' => '2',
            'title' => 'Food Sustainability',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Commerce',
            'status'=> 'Published',
        ],
        [
            'user_id' => '6',
            'title' => 'Stock markets analysis',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Commerce',
            'status'=> 'Published',
        ],
        [
            'user_id' => '1',
            'title' => 'Food Sustainability',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Business Science: Actuarial Science',
            'status'=> 'Published',
        ],
        [
            'user_id' => '5',
            'title' => 'Media conglomerates, ownership',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Arts in Communication',
            'status'=> 'Published',
        ],
        [
            'user_id' => '2',
            'title' => 'Police brutality',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Laws',
            'status'=> 'Published',
        ],
        [
            'user_id' => '3',
            'title' => 'Educating special needs students',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Commerce',
            'status'=> 'Published',
        ],
        [
            'user_id' => '1',
            'title' => 'Technology in education',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Commerce',
            'status'=> 'Published',
        ],
        [
            'user_id' => '1',
            'title' => 'Bioterrorism',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Arts in International Studies',
            'status'=> 'Published',
        ],
        [
            'user_id' => '1',
            'title' => 'Laravel Installation',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Informatics and Computer Science',
            'status'=> 'Published',
        ],
        [
            'user_id' => '2',
            'title' => 'Food Sustainability',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Business Science: Financial Engineering',
            'status'=> 'Published',
        ],
        [
            'user_id' => '3',
            'title' => 'Database Schemas',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Informatics and Computer Science',
            'status'=> 'Published',
        ],
        [
            'user_id' => '4',
            'title' => 'Do we need more international diplomats',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Arts in International Studies',
            'status'=> 'Published',
        ],
        [
            'user_id' => '5',
            'title' => 'Website Application Development Tools',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Informatics and Computer Science',
            'status'=> 'Published',
        ],
        [
            'user_id' => '5',
            'title' => 'Financial Data Analysis Tools',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Arts in Financial Services',
            'status'=> 'Published',
        ],
        [
            'user_id' => '1',
            'title' => 'Debugging a Heroku application on production',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Informatics and Computer Science',
            'status'=> 'Published',
        ],
        [
            'user_id' => '2',
            'title' => 'Food Sustainability',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Commerce',
            'status'=> 'Published',
        ],
        [
            'user_id' => '6',
            'title' => 'Stock markets analysis',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Commerce',
            'status'=> 'Published',
        ],
        [
            'user_id' => '1',
            'title' => 'Food Sustainability',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Business Science: Actuarial Science',
            'status'=> 'Published',
        ],
        [
            'user_id' => '5',
            'title' => 'Media conglomerates, ownership',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Arts in Communication',
            'status'=> 'Published',
        ],
        [
            'user_id' => '2',
            'title' => 'Police brutality',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Laws',
            'status'=> 'Published',
        ],
        [
            'user_id' => '3',
            'title' => 'Educating special needs students',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Commerce',
            'status'=> 'Published',
        ],
        [
            'user_id' => '1',
            'title' => 'Technology in education',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Commerce',
            'status'=> 'Published',
        ],
        [
            'user_id' => '1',
            'title' => 'Bioterrorism',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Arts in International Studies',
            'status'=> 'Published',
        ],
        [
            'user_id' => '1',
            'title' => 'Laravel Installation',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Informatics and Computer Science',
            'status'=> 'Published',
        ],
        [
            'user_id' => '2',
            'title' => 'Food Sustainability',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Business Science: Financial Engineering',
            'status'=> 'Published',
        ],
        [
            'user_id' => '3',
            'title' => 'Database Schemas',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Informatics and Computer Science',
            'status'=> 'Published',
        ],
        [
            'user_id' => '4',
            'title' => 'Do we need more international diplomats',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Arts in International Studies',
            'status'=> 'Published',
        ],
        [
            'user_id' => '5',
            'title' => 'Website Application Development Tools',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Informatics and Computer Science',
            'status'=> 'Published',
        ],
        [
            'user_id' => '5',
            'title' => 'Financial Data Analysis Tools',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Arts in Financial Services',
            'status'=> 'Published',
        ],
        [
            'user_id' => '1',
            'title' => 'Debugging a Heroku application on production',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Informatics and Computer Science',
            'status'=> 'Published',
        ],
        [
            'user_id' => '2',
            'title' => 'Food Sustainability',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Commerce',
            'status'=> 'Published',
        ],
        [
            'user_id' => '6',
            'title' => 'Stock markets analysis',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Commerce',
            'status'=> 'Published',
        ],
        [
            'user_id' => '1',
            'title' => 'Food Sustainability',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Business Science: Actuarial Science',
            'status'=> 'Published',
        ],
        [
            'user_id' => '5',
            'title' => 'Media conglomerates, ownership',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Arts in Communication',
            'status'=> 'Published',
        ],
        [
            'user_id' => '2',
            'title' => 'Police brutality',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Laws',
            'status'=> 'Published',
        ],
        [
            'user_id' => '3',
            'title' => 'Educating special needs students',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Commerce',
            'status'=> 'Published',
        ],
        [
            'user_id' => '1',
            'title' => 'Technology in education',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Commerce',
            'status'=> 'Published',
        ],
        [
            'user_id' => '1',
            'title' => 'Bioterrorism',
            'detail' => 'StatizenAsk is an educational networking tool dedicated to Strathmore University that will facilitate collaboration between both students and faculty. This tool will allow students to pose questions or discussions to the forum and receive feedback from their peers or faculty. With this, we aim to create an open and collaborative environment that would promote learning and student to faculty engagement.',
            'category'=> 'Bachelor of Arts in International Studies',
            'status'=> 'Published',
        ]
        ];

        foreach($posts as $post)
          {
              Post::create([
               'user_id' => $post['user_id'],
               'title' => $post['title'],
               'detail' => $post['detail'],
               'category' => $post['category'],
               'status' => $post['status'],
               'published_on' => Carbon::now()->format('Y-m-d H:i:s'),
             ]);
           }
    }
}
